### ISSUE TITLE
Separate 3DS Authentication - Design

### ISSUE THREAD

**Issue by akash-kamble-juspay** [juspay/hyperswitch-web#113]
Design 3DS Authentication flows for both Web and Mobile.
Design considering DAF, DA, SPC and CTP.

**Comment by sai-harsha-vardhan** [comment]
Flow diagram
<img width="667" alt="image" src="https://github.com/juspay/hyperswitch-web/assets/56996463/f4e1e8df-c077-4ba9-a93c-4a9ee137448e">

Link to design docs - https://docs.google.com/document/d/1bgW4z3BScPINufts2XqBUC0v23F6xy9j8RFbyxYr9ro/edit?usp=sharing
