### ISSUE TITLE
Fix: Empty email for Saved Cards

### ISSUE THREAD

**Issue by prafulkoppalkar** [juspay/hyperswitch-web#130]

**Comment by preetamrevankar** [comment]
Test cases 
Saved card payment for cybersource  

![Image](https://github.com/juspay/hyperswitch-web/assets/132073736/4d5ab0ad-c449-47b6-a01e-f9a03871ea0b)
![Image](https://github.com/juspay/hyperswitch-web/assets/132073736/73868988-7095-462f-b55b-f2614ca47c95)
