### ISSUE TITLE
Open sourcing the Native Unified Checkout SDK (Android and iOS)

### ISSUE THREAD

**Issue by akash-c-k** [juspay/hyperswitch-web#140]

**Comment by manojradhakrishnan** [comment]
1. Create a master issue to link al the work items

**Comment by akash-c-k** [comment]
- [ ] Naming the repos
- [ ] Cleaning up the code
- [ ] Release management and versioning solution
- [ ] Playground cleanup
- [ ] move hard coded keys to .envs
- [ ] git secrets
- [ ] Git submodules to connect repos
- [ ] Documentation
- [ ] Deployment pipeline setup

**Comment by akash-c-k** [comment]
Work Items delayed:

- [ ] CICD Pipeline
- [ ] Making the repo public

**Comment by akash-c-k** [comment]
- [ ] CICD pipeline
- [ ] Documentation on gitbook

**Comment by akash-c-k** [comment]
Backlogged from last week

- [ ]  CICD pipeline
- [ ]  Documentation on gitbook

**Comment by akash-c-k** [comment]
- [ ] Documentation on Gitbook backlogged from last week

**Comment by akash-c-k** [comment]
- [ ]  Documentation on Gitbook backlogged from last week

**Comment by akash-c-k** [comment]
Docs are added.
