### ISSUE TITLE
Missing documentation about setting up sdk locally

### ISSUE THREAD

**Issue by lsampras** [juspay/hyperswitch-web#331]
Currently the [documentation](https://github.com/juspay/hyperswitch-web?tab=readme-ov-file#about-env-configs) for hyperswitch-web only refers to setting up the demo app,

The environment variables mentioned above refer to those used in the demo app [here](https://github.com/juspay/hyperswitch-web/blob/main/Hyperswitch-React-Demo-App/webpack.common.js).

There doesn't seem to be documentation about the variables used in actual SDK setup [here](https://github.com/juspay/hyperswitch-web/blob/main/webpack.common.js).

referring to variables specifically here.

https://github.com/juspay/hyperswitch-web/blob/main/webpack.common.js#L11-L14

**Comment by PritishBudhiraja** [comment]
Addressed. Need few changes where ever we are using sdkEnv in our Jenkins Pipeline for running the scripts. 
https://github.com/juspay/hyperswitch-web/pull/335
