### ISSUE TITLE
Applepay - Missing details

### ISSUE THREAD

**Issue by akash-c-k** [juspay/hyperswitch-web#495]

**Comment by ArushKapoorJuspay** [comment]
Action Items -

- [ ] Add Support for the config `collect_billing_details_from_wallets`, to give the option for the merchant to either collect billing details from Wallet SDK or directly from Hyperswitch SDK in the Dynamic Fields.
- [ ] In case collecting billing details from Wallet SDK, add validation on the fields received in the response given by the Wallet SDK before sending in the confirm payload.
- [ ] Open modal to collect the invalid details sent by the Wallet SDK
- [ ] Add support for a config from the merchant to open a Modal to show all the details sent by the Wallet SDK to verify from the user
