### ISSUE TITLE
Provide docker compose support for web sdk

### ISSUE THREAD

**Issue by seekshiva** [juspay/hyperswitch-web#510]
Add Dockerfile similar to https://github.com/juspay/hyperswitch-control-center/blob/main/Dockerfile

**Comment by PritishBudhiraja** [comment]
- [ ] Create a hyperswitch-web-cloud repo for writing scripts and storing keys.
- [ ] Create a new Jenkins Pipeline to push Docker Hub from the above repo to run manual trigger based upon the tag provided.
- [ ] Write a Jenkins script for Docker Hub.
- [ ] Pipeline setup
