### ISSUE TITLE
fix passing customer acceptance during CIT transactions for Bank Debits 

### ISSUE THREAD

**Issue by srujanchikke** [juspay/hyperswitch-web#513]
CIT (Customer initiated transaction ) requires customer acceptance incase of "setup_future_usage": "off_session" . Currently we are passing it for cards , we didn't find customer acceptance being passed incase of bank debits .

@Gnanasundari24 tested it for Adyen bank debits(SEPA ).

**Comment by PritishBudhiraja** [comment]
![Screenshot 2024-07-24 at 12 23 03 PM](https://github.com/user-attachments/assets/6e395d20-c4aa-48d3-bf02-acbb0e2eea2d)


We can see that we are passing customer_acceptance. Can you please inform for which bank_debit the issue came.
