### ISSUE TITLE
Apple Pay Setup Doc via Ngrok

### ISSUE THREAD

**Issue by PritishBudhiraja** [juspay/hyperswitch-web#521]

**Comment by ArushKapoorJuspay** [comment]
[ApplePay Local Setup Doc Link](https://docs.google.com/document/d/1hAkU0kURlLyTJPboexxL1DBSUwHT4Ltt-ufTwI0REH8/edit?usp=sharing)

**Comment by PritishBudhiraja** [comment]
Is the local setup also there? Via local host I can do the changes and test it? 
@ArushKapoorJuspay
