### ISSUE TITLE
X url on website hasn't been updated.

### ISSUE THREAD

**Issue by BishalJena** [juspay/hyperswitch-web#531]
Bug Description
![image](https://github.com/user-attachments/assets/bb6da603-0d96-466b-9a49-71a50bf7fa4c)

Expected Behavior
It should be "https://x.com/HyperSwitchIO"

Actual Behavior
it actually is "https://twitter.com/HyperSwitchIO"
There are chances of twitter.com/links deprecating so we should change this.

Steps To Reproduce
Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.

Go to footer section of webpage
Hover on X icon
You'll see "https://twitter.com/HyperSwitchIO"

Have you spent some time checking if this bug has been raised before?
 I checked and didn't find a similar issue
Have you read the Contributing Guidelines?
 I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)
Are you willing to submit a PR?
Yes, I am willing to submit a PR!

**Comment by PritishBudhiraja** [comment]
Thanks for the update. We have fixed this issue on our website.
