### ISSUE TITLE
paypal via braintree --or pay using label is displayed even when wallet payment buttons are not present on the checkout page

### ISSUE THREAD

**Issue by preetamrevankar** [juspay/hyperswitch-web#733]
![Image](https://github.com/user-attachments/assets/36fe13ab-b39f-4c1c-aa6e-211f163e70f3)

steps to reproduce 
1. Bank of america connector>> Remove billing address >>>Allconnector123

**Comment by preetamrevankar** [comment]
PayPal via Braintree, PayPal button is not rendering.

Blocked on Backend to verify whether Braintree PayPal is currently supported

**Comment by PritishBudhiraja** [comment]
Duplicate issue. Already closed. As this is not even an issue as PayPal via braintree is button is not rendering but backend is sending as AllConnector123 is an old account so it will only happen in that case only.
